[agent]
  interval = "10s"
  flush_interval = "5s"
  omit_hostname = true
  skip_processors_after_aggregators = false

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["${MQTT_TOPIC}"]
  client_id = "telegraf-cultivia"
  username = "telegraf"
  password = "${MQTT_TELEGRAF_PASSWORD}"
  qos = 0
  topic_tag = "topic"
  name_override = "estufa"

  # deixei tudo optional pq o esp32 não manda os botões
  data_format = "json_v2"
  [[inputs.mqtt_consumer.json_v2]]
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "modo"
      type = "string"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "temperatura_simulada"
      type = "float"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "umidade_simulada"
      type = "float"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "temperatura_ideal"
      type = "float"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "umidade_ideal"
      type = "float"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "botao_a"
      type = "int"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "botao_c"
      type = "int"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "joystick_sw"
      type = "int"
      optional = true
